name: Job Monitor

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send WeChat Message
        run: |
          curl -X POST "${{ secrets.WECHAT_WEBHOOK }}" \
          -H "Content-Type: application/json" \
          -d '{
                "msgtype": "text",
                "text": {
                  "content": "GitHub Actions 测试成功 ✅"
                }
              }'
